version: 2
registries:
  github-actonomy:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPNDA_GITHUB_PERSONAL_TOKEN}}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - github-actonomy
